# -*- coding: utf-8 -*-
"""gridlock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lGT96OBpb06sXO8O8KOhaXD9lQhkTAQD
"""

!pip install catboost

from google.colab import files

uploaded = files.upload()

!pip install catboost -q

import pandas as pd
from catboost import CatBoostRegressor

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

print(train.shape)
print(test.shape)

import pandas as pd
from catboost import CatBoostRegressor

train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

for df in [train, test]:
    df["hour"] = df["timestamp"].str.split(":").str[0].astype(int)
    df["minute"] = df["timestamp"].str.split(":").str[1].astype(int)
    df["time_slot"] = df["hour"] * 60 + df["minute"]

for col in train.columns:
    if col == "demand":
        continue

    if train[col].dtype == "object":
        train[col] = train[col].fillna("Missing")
        test[col] = test[col].fillna("Missing")
    else:
        median = train[col].median()
        train[col] = train[col].fillna(median)
        test[col] = test[col].fillna(median)

y = train["demand"]

X = train.drop(["demand", "Index", "timestamp"], axis=1)
X_test = test.drop(["Index", "timestamp"], axis=1)

cat_features = [
    X.columns.get_loc(col)
    for col in X.select_dtypes(include="object").columns
]

model = CatBoostRegressor(
    iterations=1000,
    depth=8,
    learning_rate=0.05,
    verbose=100
)

model.fit(X, y, cat_features=cat_features)

preds = model.predict(X_test)

submission = pd.DataFrame({
    "Index": test["Index"],
    "demand": preds
})

submission.to_csv("submission.csv", index=False)

print("DONE! submission.csv created")

from google.colab import files
files.download("submission.csv")

print(train.columns.tolist())

train.head()

geo_mean = train.groupby("geohash")["demand"].mean()
train["geo_mean_demand"] = train["geohash"].map(geo_mean)
test["geo_mean_demand"] = test["geohash"].map(geo_mean)
global_mean = train["demand"].mean()
test["geo_mean_demand"] = test["geo_mean_demand"].fillna(global_mean)

road_mean = train.groupby("RoadType")["demand"].mean()

train["road_mean_demand"] = train["RoadType"].map(road_mean)
test["road_mean_demand"] = test["RoadType"].map(road_mean)

model = CatBoostRegressor(
    iterations=3000,
    depth=10,
    learning_rate=0.03,
    loss_function="RMSE",
    random_seed=42,
    verbose=200
)

print(train["geohash"].nunique())
print(train["RoadType"].value_counts())
print(train["Weather"].value_counts())

geo_mean = train.groupby("geohash")["demand"].mean()
train["geo_mean"] = train["geohash"].map(geo_mean)
test["geo_mean"] = test["geohash"].map(geo_mean)
train["geo_mean"] = train["geo_mean"].fillna(train["demand"].mean())
test["geo_mean"] = test["geo_mean"].fillna(train["demand"].mean())
geo_count = train["geohash"].value_counts()
train["geo_count"] = train["geohash"].map(geo_count)
test["geo_count"] = test["geohash"].map(geo_count).fillna(0)

model = CatBoostRegressor(
    iterations=4000,
    depth=10,
    learning_rate=0.03,
    loss_function="RMSE",
    random_seed=42,
    verbose=200
)

from google.colab import files
files.download("submission.csv")

print(train["day"].value_counts())

print(train.groupby("day")["demand"].mean())

print(train.groupby(["geohash", "timestamp"])["demand"].count().describe())

print(
    train.groupby(["geohash", "timestamp"])["demand"]
    .std()
    .describe()
)

print("TRAIN MISSING VALUES")
print(train.isnull().sum())
print("\nTEST MISSING VALUES")
print(test.isnull().sum())
print("\nTRAIN GEOHASHES")
print(train["geohash"].nunique())
print("\nTEST GEOHASHES")
print(test["geohash"].nunique())
print("\nUNSEEN GEOHASHES")
print(len(set(test["geohash"]) - set(train["geohash"])))
print("\nTRAIN TIMESTAMPS")
print(train["timestamp"].nunique())
print("\nTEST TIMESTAMPS")
print(test["timestamp"].nunique())
print("\nDAY COUNTS")
print(train["day"].value_counts())
print("\nDEMAND BY WEATHER")
print(train.groupby("Weather")["demand"].mean())
print("\nDEMAND BY ROADTYPE")
print(train.groupby("RoadType")["demand"].mean())
print("\nDEMAND BY LANES")
print(train.groupby("NumberofLanes")["demand"].mean())
print("\nDEMAND BY LARGE VEHICLES")
print(train.groupby("LargeVehicles")["demand"].mean())
print("\nDEMAND BY LANDMARKS")
print(train.groupby("Landmarks")["demand"].mean())

train["road_lane"] = train["RoadType"].astype(str) + "_" + train["NumberofLanes"].astype(str)
test["road_lane"] = test["RoadType"].astype(str) + "_" + test["NumberofLanes"].astype(str)

train["geo_weather"] = train["geohash"].astype(str) + "_" + train["Weather"].astype(str)
test["geo_weather"] = test["geohash"].astype(str) + "_" + test["Weather"].astype(str)

model.fit(X, y, cat_features=cat_features)

preds = model.predict(X_test)

submission = pd.DataFrame({
    "Index": test["Index"],
    "demand": preds
})

submission.to_csv("submission.csv", index=False)

print("DONE!")

from google.colab import files
files.download("submission.csv")